### ISSUE TITLE
python compatiblity?

### ISSUE THREAD

**Issue by juzza88** [greenweb-cloud/prometheus_exporters#12]
[root@pw-docker site-packages]# hpilo-exporter --address=0.0.0.0 --port=9416 --endpoint="/metrics"
Traceback (most recent call last):
  File "/usr/local/bin/hpilo-exporter", line 11, in <module>
    load_entry_point('hpilo-exporter==0.4.5', 'console_scripts', 'hpilo-exporter')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, na

is this supports for python 3.6 or a specific version or?

**Comment by rezabojnordi** [comment]
unfortunately, it only supports python2 but right now it's on our plan to develop it in order to support python3.
