### ISSUE TITLE
SyntaxError: multiple exception types must be parenthesized (python 3.10 & pip 22.0.2)

### ISSUE THREAD

**Issue by aknypl** [greenweb-cloud/prometheus_exporters#39]
pip install hpilo-exporter  

Collecting hpilo-exporter
  Using cached hpilo_exporter-0.4.5-py3-none-any.whl
Requirement already satisfied: python-hpilo in /etc/hpilo/hp1/lib/python3.10/site-packages (from hpilo-exporter) (4.4.3)
Requirement already satisfied: prometheus-client in /etc/hpilo/hp1/lib/python3.10/site-packages (from hpilo-exporter) (0.16.0)
Installing collected packages: hpilo-exporter
Successfully installed hpilo-exporter-0.4.5

# hpilo-exporter            

Traceback (most recent call last):
  File "/etc/hpilo/hp1/bin/hpilo-exporter", line 5, in <module>
    from hpilo_exporter.main import main
  File "/etc/hpilo/hp1/lib/python3.10/site-packages/hpilo_exporter/main.py", line 7, in <module>
    from hpilo_exporter.exporter import ILOExporterServer
  File "/etc/hpilo/hp1/lib/python3.10/site-packages/hpilo_exporter/exporter.py", line 64
    except KeyError, e:
           ^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

pip --version
pip 22.0.2 from /etc/hpilo/hp1/lib/python3.10/site-packages/pip (python 3.10)

**Comment by srkaviani** [comment]
hi
please remove the old hpilo_exporter version
` pip uninstall hpilo_exporter `
and then install latest version of exporter with this command:
` bash <(curl -Ls https://raw.githubusercontent.com/hpilo-exporter/hpilo-exporter/master/install.sh)
 `
